# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@root" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/nix/store" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@nix/store" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@var" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@var/log" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@var/cache" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@var/tmp" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/60417b11-7d0f-4bc7-a3c1-b4ffc5f10d57";
      fsType = "btrfs";
      options = [ "subvol=@swap" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/3F73-5DCA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/8bdbb302-76d7-40b7-8360-13fc04923381";
      fsType = "btrfs";
      options = [ "subvol=@data" "noatime" "autodefrag" "compress=zstd:15" ];
    };

  swapDevices = [{ device = "/swap/swapfile"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
